import { constants } from "node:fs";
import { access } from "node:fs/promises";
import { resolve } from "node:path";

import {
  applyAtomicTextWrite,
  planAtomicTextUpdate,
  type PlannedTextWrite,
} from "./atomic-file.js";
import { RuntimeFailure } from "./errors.js";
import {
  getDistribution,
  type ClientLauncher,
} from "./distribution.js";

export type ClientTarget = "codex" | "claude-code" | "deepseek-harness";

export interface ConfigureClientOptions {
  readonly target: ClientTarget;
  readonly projectPath?: string;
  readonly serverPath?: string;
}

export interface ClientConfigurationResult {
  readonly ok: true;
  readonly target: ClientTarget;
  readonly path: string;
  readonly serverPath: string | null;
  readonly launcher: ClientLauncher;
  readonly operation: "created" | "updated" | "unchanged";
}

export interface ClientConfigurationPlan {
  readonly result: Omit<ClientConfigurationResult, "operation">;
  readonly write: PlannedTextWrite;
}

const CODEX_START = "# >>> godot-agent-runtime managed section >>>";
const CODEX_END = "# <<< godot-agent-runtime managed section <<<";
const DEEPSEEK_HARNESS_PATCH = ".dsh/godot-agent-runtime.patch.yml";

function codexConfiguration(
  existing: string | null,
  launcher: ClientLauncher,
  projectPath: string,
): string {
  const block = [
    CODEX_START,
    "[mcp_servers.godot-agent-runtime]",
    `command = ${JSON.stringify(launcher.command)}`,
    `args = [${launcher.args.map((argument) => JSON.stringify(argument)).join(", ")}]`,
    `cwd = ${JSON.stringify(projectPath)}`,
    CODEX_END,
  ].join("\n");
  if (existing === null || existing.trim() === "") return `${block}\n`;

  const start = existing.indexOf(CODEX_START);
  const end = existing.indexOf(CODEX_END);
  if ((start === -1) !== (end === -1) || (start !== -1 && end < start)) {
    throw new RuntimeFailure({
      code: "CLIENT_CONFIG_MANAGED_SECTION_INVALID",
      stage: "configuration",
      message: "The Codex configuration contains an incomplete managed section.",
      details: { startMarker: CODEX_START, endMarker: CODEX_END },
      recovery: ["Repair or remove only the godot-agent-runtime managed marker section, then retry."],
    });
  }
  if (start !== -1) {
    const after = end + CODEX_END.length;
    return `${existing.slice(0, start)}${block}${existing.slice(after)}`;
  }
  return `${existing.trimEnd()}\n\n${block}\n`;
}

function claudeConfiguration(existing: string | null, launcher: ClientLauncher): string {
  let root: Record<string, unknown> = {};
  if (existing !== null && existing.trim() !== "") {
    try {
      const parsed: unknown = JSON.parse(existing);
      if (typeof parsed !== "object" || parsed === null || Array.isArray(parsed)) throw new Error("root is not an object");
      root = parsed as Record<string, unknown>;
    } catch (error) {
      throw new RuntimeFailure({
        code: "CLIENT_CONFIG_INVALID_JSON",
        stage: "configuration",
        message: "The existing Claude Code .mcp.json is not a JSON object.",
        details: { cause: error instanceof Error ? error.message : String(error) },
        recovery: ["Fix .mcp.json before retrying so unrelated MCP server entries can be preserved."],
      });
    }
  }
  const existingServers = root.mcpServers;
  const mcpServers =
    typeof existingServers === "object" && existingServers !== null && !Array.isArray(existingServers)
      ? { ...(existingServers as Record<string, unknown>) }
      : {};
  mcpServers["godot-agent-runtime"] = {
    type: "stdio",
    command: launcher.command,
    args: [...launcher.args],
  };
  return `${JSON.stringify({ ...root, mcpServers }, null, 2)}\n`;
}

function deepseekHarnessConfiguration(
  launcher: ClientLauncher,
  projectPath: string,
): string {
  return [
    "# Generated by godot-agent-runtime. Re-run configure deepseek-harness to update.",
    "- insert:",
    "    - id: mcp-godot-agent-runtime",
    "      name: '@deepseek-ai/dsh-mcp-client'",
    "      config:",
    "        serverName: godot",
    "        transport: stdio",
    `        command: ${JSON.stringify(launcher.command)}`,
    "        args:",
    ...launcher.args.map((argument) => `          - ${JSON.stringify(argument)}`),
    `        cwd: ${JSON.stringify(projectPath)}`,
    "        toolCallTimeoutMs: 120000",
    "        failOnStartupError: true",
    "",
  ].join("\n");
}

export async function planClientConfiguration(
  options: ConfigureClientOptions,
): Promise<ClientConfigurationPlan> {
  const projectPath = resolve(options.projectPath ?? process.cwd());
  const explicitServerPath = options.serverPath === undefined
    ? null
    : resolve(options.serverPath);
  const distribution = explicitServerPath === null ? getDistribution() : null;
  const serverPath = explicitServerPath ?? distribution?.mcpServerPath ?? null;
  const launcher: ClientLauncher = explicitServerPath === null
    ? distribution!.mcpLauncher
    : { command: process.execPath, args: [explicitServerPath] };
  const targetPath =
    options.target === "codex"
      ? resolve(projectPath, ".codex", "config.toml")
      : options.target === "deepseek-harness"
        ? resolve(projectPath, DEEPSEEK_HARNESS_PATCH)
        : resolve(projectPath, ".mcp.json");
  if (explicitServerPath !== null) {
    try {
      await access(explicitServerPath, constants.R_OK);
    } catch (error) {
      throw new RuntimeFailure({
        code: "CLIENT_SERVER_NOT_BUILT",
        stage: "configuration",
        message: `The MCP server entrypoint was not found at ${explicitServerPath}.`,
        details: {
          serverPath: explicitServerPath,
          cause: error instanceof Error ? error.message : String(error),
        },
        recovery: ["Run the repository build, or pass --server with the absolute MCP server entrypoint."],
      });
    }
  }
  const write = await planAtomicTextUpdate(targetPath, (existing) =>
    options.target === "codex"
      ? codexConfiguration(existing, launcher, projectPath)
      : options.target === "deepseek-harness"
        ? deepseekHarnessConfiguration(launcher, projectPath)
        : claudeConfiguration(existing, launcher));
  return {
    result: {
      ok: true,
      target: options.target,
      path: targetPath,
      serverPath,
      launcher,
    },
    write,
  };
}

export async function applyClientConfigurationPlan(
  plan: ClientConfigurationPlan,
): Promise<ClientConfigurationResult> {
  const operation = await applyAtomicTextWrite(plan.write);
  return { ...plan.result, operation };
}

export async function configureClient(
  options: ConfigureClientOptions,
): Promise<ClientConfigurationResult> {
  return await applyClientConfigurationPlan(
    await planClientConfiguration(options),
  );
}
